version: '3.9'

services:
  web:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    command: >
        sh -c "python manage.py migrate &&
        gunicorn django_weather.wsgi:application 0.0.0.0:8000"
    depends_on:
      - db


  db:
    image: postgres:14
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
